# Global Paramaters
num_cycles: 1
exp_time: 30s # accepts int number of (s)econds or (m)inutes

# Default algorithms to use for each server if not specified 
default: &default
  - tcp/cubic

# Algorithms to run on each server (leave blank for default)
# Format: PROTO/ALG K=V K=V K=V
# (exp_time can be provided as a key to override global)

servers:
  - 13.56.224.25:
    - tcp/ccp-nimbus useSwitching=false bwEstMode=true exp_time=35s

# Available algorithms and parameters
# 
# cubic
# reno
# vegas
# bbr
# ccp-nimbus
#   useSwitching      true/false, whether or not to use switching, default=false
#   bwEstMode         true/false, whether or not to use bw est, default=true
#   delayThreshold    threshold for delay control rule, default=1.25
#   xtcpFlows         number of flows in bundle, default=10
#   frequency					frequency of pulses, default=5.0
#   pulseSize					size of pulse as fraction of current rate, defaeult=0.25
#   switchingThresh   value of elasticity for switching modes, default=0.4
# ccp-cubic
# ccp-reno
# ccp-vegas
# ccp-bbr
# remy
#   linkrate          assumed training link rate in mbps
#   train_length      number of packets in packet train for bw est
#   remycc            name of remycc file to use 
