#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

last_version=$(git log --oneline -1 | cut -d "[" -f2 | cut -d "]" -f1)
new_version=$(.git/hooks/get-next-version)
sed -i'.tmp' "s/$last_version/$new_version/g" client/main.go
rm client/main.go.tmp
git add client/main.go
